name: Generate Github Release Changelog

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
          
    - name: Generate Release Body
      run: npx extract-changelog-release > RELEASE_BODY.md
      
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        bodyFile: "RELEASE_BODY.md"
        token: ${{ secrets.GITHUB_TOKEN }}